version: "3.5"
services:
  db:
    image: postgres:12.6
    ports:
      - "5433:5432"
    restart: always
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    healthcheck:
      test: /usr/bin/pg_isready -U ${POSTGRES_ADMIN_USER}
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_home:/var/lib/postgresql/data

  # nocodb:
  #   image: nocodb/nocodb:latest
  #   ports:
  #     - "8080:8080"

  # pgadmin:
  #   image: dpage/pgadmin4:6
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   volumes:
  #     - ./volumes/pgadmin:/var/lib/pgadmin

  # wait:
  #   image: dokku/wait

  # cache:
  #   container_name: cache
  #   image: redis:6
  #   # networks:
  #   #   - directus

  # directus:
  #   container_name: directus
  #   image: directus/directus:latest
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     # By default, uploads are stored in /directus/uploads
  #     # Always make sure your volumes matches the storage root when using
  #     # local driver
  #     - ./uploads:/directus/uploads
  #     # Make sure to also mount the volume when using SQLite
  #     # - ./database:/directus/database
  #     # If you want to load extensions from the host
  #     # - ./extensions:/directus/extensions
  #   # networks:
  #   #   - directus
  #   depends_on:
  #     - cache
  #     - database
  #   environment:
  #     KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
  #     SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

  #     DB_CLIENT: "pg"
  #     DB_HOST: "db"
  #     DB_PORT: "5432"
  #     DB_DATABASE: ${POSTGRES_DB}
  #     DB_USER: ${POSTGRES_ADMIN_USER}
  #     DB_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

  #     CACHE_ENABLED: "true"
  #     CACHE_STORE: "redis"
  #     CACHE_REDIS: "redis://cache:6379"

  #     ADMIN_EMAIL: "admin@example.com"
  #     ADMIN_PASSWORD: "d1r3ctu5"

  #     # Make sure to set this in production
  #     # (see https://docs.directus.io/reference/environment-variables/#general)
  #     # PUBLIC_URL: 'https://directus.example.com'

volumes:
  db_home:
    external: false
