[package]
edition = "2018"
license = "Apache-2.0/MIT"
name = "partial_struct"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.3"
syn = "0.11.11"

[dev-dependencies]
serde = {version = "1.0.130", features = ["derive", "rc"]}
serde_json = {version = "1.0.68"}
